language: node_js
node_js:
- '0.10'
before_script:
- echo '{}' > ${HOME}/elastic.json
- touch ${HOME}/.env
- npm install -g grunt-cli
- ./create_config.sh
script:
- npm test
- node lib/run.js --projectKey ${SPHERE_PROJECT_KEY} --clientId ${SPHERE_CLIENT_ID}
  --clientSecret ${SPHERE_CLIENT_SECRET} --output out.xml
notifications:
  hipchat:
    rooms:
      secure: qI9x6s4eS8zBB4yz5Qgpk66+E4879Q9XP9BnIRYDwHfCRaGvq/H2b3E78gtCDwAhJO+OyoJz5ciScULjx9Y32KaT0x4OdgdIrfJuvpNJBObaveuov8rgEE7vd8JxW5SpugEhW7eebLbxDac8HEZ/wG83IXs3TRXMiPCT1ZdB9GY=
    template:
    - ! '%{repository}#%{build_number} (%{author}): %{message} (<a href="%{build_url}">Details</a>
      <a href="%{compare_url}">Compare</a>)'
    format: html
    on_success: change
    on_failure: change
env:
  global:
  - secure: cLZngx/MvWNY2+8yc18+4fxpo/d6m3BpEKO+kg3NORu7fA5RacDNCBcgAMQfmQLQgJ0yKpbCbKVvZ6gplLOSMMGc8N0x/5uDuPuGZaqDPL4cTJ4YQHo49yDVimxpygsfOQ4AdPsge2ZZhyQya29qDMETdcwXNaQGCNxTcE0oKVI=
  - secure: eq0G7z600Bq+ymoK+VnEDLQNJkzfujcQ4CtqerZ/t6O+Igh4F6c94eoTeUb6mxsnbeuuP+S6VyWz6zZHxa1Hh+KnPPPVBmBPxbAaFUrHsN0HmCuTKugu7jQq/92zjsyYdT3gqjh1Twfzp3SvhjhvKllEedpRZ3v07TzKS3a3fn8=
  - secure: KxM59wAUKoFIJ2ZN0TD7Qj2Eb9MlZK7p+v/OmjYPFb2RxkKydv3Sd8en2n2ffLX8Orv/Qntj5wHfBTGTa9MkYwMInGfcgkixCZh/IPUMQwcpDIl6b7/yS2V8zqeuig8gzCvJlAteo7yHyBBcIto9eWLWnki584/m+C2LWKq1q4Q=
